### ISSUE TITLE
[FIX] 유튜브 경기 영상 주소 통일

### ISSUE THREAD

**Issue by seongminn** [hufscheer/client_v2#172]
## 배경

유저가 입력할 수 있는 유튜브 주소가 통일되지 않습니다. 이로 인해 유효성 검사에 문제가 발생합니다.

## 할 일

- [x] 경기 영상 유효성 검사 수정

**Comment by ohprettyhak** [comment]
저도 겪고있는 문제인데, `https://youtu.be/` 링크에 대해서도 대응이 되면 좋을 듯 합니다!
