### ISSUE TITLE
[FEAT]: 관객 응원톡 컴포넌트 추가

### ISSUE THREAD

**Issue by ohprettyhak** [hufscheer/client_v2#27]
- [ ] `breakpoint` 를 `@hcc/styles`로 접근 가능하게 변경
- [ ] 모달 (범용으로 사용 가능하도록 `@hcc/ui`에 추가)
> <img width="469" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/96096fc1-33fa-491a-abb7-bc93804f6874">

- [ ] 응원톡 버튼 (FloatingLinkButton)
> <img width="68" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/b61d4c2a-4b0f-4a07-8b03-92e9602d5f63">

- [ ] 응원톡 상단 스코어 (FloatingScoreCard)
> <img width="505" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/9c4238f3-293f-4f4c-96c5-577bf32c6c65">

- [ ] 응원톡 내부 채팅 디자인
> <img width="404" alt="image" src="https://github.com/hufscheer/client_v2/assets/97780352/6bb6bba3-97b1-46fc-81ce-27dab20ecad5">

`FloatingLinkButton`, `FloatingScoreCard` 의 경우 `FAB(Floating Action Button`라고 불리는 컴포넌트와 모양이 비슷해 임시로 붙인 이름입니다. 더 좋은 의견 있다면 반영하겠습니다!

**Comment by HiimKwak** [comment]
혹시 이거 이슈 올릴 때 피그마 와이어프레임이나 시각적으로 참고할만한 자료가 있으면 함께 첨부해주실 수 있나요?

예를 들어 모달의 경우 - 모든 곳에서 쓰일 수 있는 모달 프로토타입을 만들겠다는 뜻인지, 특정 와이어프레임 페이지에서 쓰이는 모달을 만들겠다는건지 구분이 가지 않습니다. 좀 더 자세하게 기입해주시면 원활한 작업 분배가 될 것 같아요! @ohprettyhak

**Comment by ohprettyhak** [comment]
> 혹시 이거 이슈 올릴 때 피그마 와이어프레임이나 시각적으로 참고할만한 자료가 있으면 함께 첨부해주실 수 있나요?
> 
> 예를 들어 모달의 경우 - 모든 곳에서 쓰일 수 있는 모달 프로토타입을 만들겠다는 뜻인지, 특정 와이어프레임 페이지에서 쓰이는 모달을 만들겠다는건지 구분이 가지 않습니다. 좀 더 자세하게 기입해주시면 원활한 작업 분배가 될 것 같아요! @ohprettyhak
> 
> * 추가로 작업 목록들을 살펴보니 응원톡 기능과 관련된 작업목록인 것 같아서 이슈 이름도 응원톡 관련으로 다시 작성해주시면 좋을 것 같습니다!
> * `FAB` 컴포넌트가 우리 프로젝트에 원래 존재하는 컴포넌트인가요? 아니면 본래 응원톡 버튼같은 컴포넌트를 `Floating Action Button`이라 일컫나요?
> * 응원톡 상단 스코어는 제가 생각하기에 `Banner` 단어와 잘 어울린다고 생각해 `ScoreBanner` 혹은 `CheertalkScoreBanner`, 줄여서 `CTScoreBanner` 이런식으로 작명하는게 낫지 않을까 싶습니다!

- 컴포넌트 관련하여 와이어프레임 및 설명 추가했습니다.
- `FAB`의 경우 구글의 머티리얼 디자인에 도입된 UI 요소의 이름으로 알고 있습니다. 응원톡 버튼에 굳이 `FAB` 키워드가 들어가지 않아도 될 거 같아서, 조금 더 직관적인 이름을 생각해 보겠습니다.
- `Cheertalk` 단어를 사용하여, `CheertalkScoreBanner`로 추가하도록 하겠습니다.

**Comment by HiimKwak** [comment]
반영 감사합니다. 그런데 또 생각이 드는게 있어 적어보겠습니다.
- 응원톡 버튼의 컴포넌트명이 `FloatingLinkButton`인게 살짝 와닿지 않는다 생각하는데요, 이참에 컴포넌트 디자인 - 사용에 이런 멘탈모델을 세워두면 어떨까 싶어 제안해봅니다
---
![image](https://github.com/hufscheer/client_v2/assets/87803596/84c6ee9b-3790-44f1-a540-199bbfd0a10d)

#### 앞으로 범용 컴포넌트에 대한 명칭을 `원형(a.k.a 프로토타입)`으로 명명하는 것을 제안합니다.

사실 이 멘탈모델은 위 캡쳐의 원글인 [자바스크립트는 왜 프로토타입을 선택했을까](https://medium.com/@limsungmook/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-%EC%99%9C-%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85%EC%9D%84-%EC%84%A0%ED%83%9D%ED%96%88%EC%9D%84%EA%B9%8C-997f985adb42)라는 컬럼에서 착안한 것인데요,
바로 우리의 상황에서 '응원톡 버튼'은 그 기능이 '화면에 떠있다(floating)', '클릭하면 다른 페이지로 이동한다(link & button)'로 이루어져있기 때문에 제안해주신 것처럼 `FloatingLinkButton`으로 명명하는 것이 맞다 생각합니다.
그러나 `FloatingLinkButton`을 그대로 응원톡 버튼과 동치시키는 것은 맞지 않다고 생각합니다. 범용 컴포넌트는 다양한 상황에 대처하기 위해 모호하고 뚜렷하지 않게 제작이 돼있다면, 범용 컴포넌트의 실제 형상 중 하나인 '응원톡 버튼'의 경우 그 모습과 기능이 뚜렷하고 확정돼있습니다. 그래서 `CheertalkButton`따위로 명명하는 것이 더 정확하다 생각합니다.

사실 제가 이렇게 말하지 않아도 제가 말한 방식대로 작업하시리라 믿습니다만, 제가 앞서 코멘트를 단 내용 중에 `CheertalkScoreBanner` 관련한 내용이 혼돈을 드릴 수 있을 것 같아 정정코자 코멘트를 남겼습니다. `CheertalkScoreBanner`의 경우에도 곧바로 `CheertalkScoreBanner`로 귀속시키기보다 `GameBanner`따위의 프로토타입 컴포넌트를 만들어 재사용하는 것이 바람직하지 않을까 싶습니다.

---
짧게 정리하자면 아래와 같이 바꿔주시는게 모두에게 확실하지 않을까 싶습니다.
- 응원톡 버튼(`FloatingLinkButton` - `CheertalkButton`)
- 응원톡 점수 배너(`GameBanner(예시)` - `CheertalkScoreBanner`)

이렇게 작성하면 프로토타입 컴포넌트도 만들고, 그 프로토타입을 베이스로 실제 사용처에 나타나있는 대로 실제화시키겠구나 예상할 수 있지 않을까 싶습니다!

다소 두서없이 철학적인 이야기를 드려서 난해하게 다가갈 수 있을 것 같습니다만 제 뜻이 전달되었기를 바랍니다.

**Comment by ohprettyhak** [comment]
- [ ] `px`값을 `pem`으로 변환하는 함수 `@hcc/styles`에 추가
- [ ] `comment`로 되어 있는 용어를 `cheertalk`으로 변경

포함하여 작업하겠습니다!
