### ISSUE TITLE
[REFACTOR] 관객 어플리케이션 웹 접근성 개선

### ISSUE THREAD

**Issue by seongminn** [hufscheer/client_v2#65]
## 배경

관객 앱에서 사용되는 버튼 및 아이콘에 이름이 없습니다. 때문에 스크린 리더를 사용하는 유저들은 올바른 버튼의 활용을 하기 어렵습니다. 또, 무분별하게 Next/Image의 priority 속성을 사용하고 있기 때문에 우선순위를 부여하는 의미가 퇴색되었습니다.

뿐만 아니라 자잘하게 수정해야 하라 부분들을 수정합니다.

- next/image
  - 무분별한 priority 속성 제거 + lazy loading 추가
  - placeholder blur 옵션은 추후 고민해보겠습니다.
  - 이미지 최적화 형식을 webp에서 avif로 변환하는 것을 제안합니다. avif가 webp에 비해 20% 가볍다고 합니다!
- sidebar style
- CheerTalk 컴포넌트 내부 구조
- 사용되지 않는 파일 제거
  - app/game/[id]/page.tsx -> CheerTalkModal
  - Vercel Analytics
- CheerTalk 컴포넌트 내부 구조 수정
  - 지난 PR 리뷰에서 제가 설명을 잘못 드렸는데, CheerTalk 내부에 `/_components`라는 디렉토리가 굳이 없어도 될 것 같습니다.
  - 이유는, CheerTalk이 라우터가 아니라 컴포넌트이기 때문입니다.
  - 따라서 다음과 같은 구조가 될 것 같습니다.
  ```
  _components/CheerTalk
    |- EntryButton/
    |- Modal/
    |- Form/
    |- List/
    |- OnAir/
    |- ...
    |- index.tsx
    |- CheerTalk.css.ts
  ```
  - 해당 구조에 대해 의견 남겨주시면 감사하겠습니다! @ohprettyhak 

## 할 일

- [x] aria-label 속성 추가
- [x] next/image priority를 적절하게 사용하고, lazy loading 처리
  - 이 부분은 placeholder의 blur 옵션으로 이미지 블러 효과를 제공할 수도 있습니다.
- [x] webp -> avif
- [x] vercel analytics 제거
- [x] app/game/[id]/page.tsx의 CheerTalkModal 컴포넌트 제거
- [x] sidebar style 수정
- [x] CheerTalk 디렉토리 구조 수정

**Comment by ohprettyhak** [comment]
CheerTalk 컴포넌트 부분은 지금 제안주신 방법이 처음 제가 이해한 구조이기 때문에 변경해도 좋을 거 같습니다!
