### ISSUE TITLE
[REFACTOR]: 레거시 코드 모노레포로 이전

### ISSUE THREAD

**Issue by HiimKwak** [hufscheer/client_v2#9]
- [x] manager 앱 관련 코드 이전
  - [x] api
  - [x] app
  - [x] components
  - [x] constants
  - [x] hooks - packages로 이전
  - [x] queries
  - [x] types
  - [x] utils - packages로 이전
- [ ] spectator 앱 관련 코드 이전
  - [ ] api
  - [x] app
  - [x] components
  - [x] constants
  - [x] hooks - packages로 이전
  - [x] queries
  - [x] types
  - [x] utils - packages로 이전

**Comment by HiimKwak** [comment]
manager용 모듈(components, api, queries 등)의 위치
- `/manager/app` 아래에?: app 내부가 지저분해지는 단점
- `/manager` 아래에?: app 내부를 깨끗하게 유지 가능, 다만 app 외부에 모듈을 두는게 적절한지 확인 필요

**Comment by seongminn** [comment]
컨벤션이기 때문에 개인적인 선호도를 말씀드리자면 다음과 같습니다. (components 디렉토리로 예를 들겠습니다.)

1. app 디렉토리 바깥에 components 디렉토리를 두고 해당 워크 스페이스에서 사용하는 공용 컴포넌트를 선언
  - `packages/ui`와는 구분됨
  - ex) manager 워크스페이스에서는 공용으로 사용되지만 spectators 워크스페이스에서는 사용되지 않는 컴포넌트
    - 만약 그런 컴포넌트가 없다면 존재하지 않아도 될 것 같습니다.
2. app/ 디렉토리 내부를 라우팅 파일 및 디렉토리로 구성하고, 해당 페이지에서만 사용하는 컴포넌트는 `_` prefix를 사용한 private components로 선언

이렇게 했을 때 장점은 같은 관심사를 갖고 있는 파일을 가까운 곳에 위치하도록 하여 불필요하게 폴더 구조를 왔다갔다 하지 않아도 된다는 점입니다. 이런 사소한 부분이 DX에도 영향을 줄 수 있다고 생각해요. 

또 공용 컴포넌트의 경우에는 각 페이지와 결합을 느슨하게 하는 것이 좋다고 생각하는데, 그런 점에서 보자면 app 디렉토리 바깥에 둠으로써 관심사 분리를 할 수 있다고 생각합니다.

어떻게 생각하시는지 궁금합니다!

**Comment by ohprettyhak** [comment]
제가 선호하는 방식도 성민님의 의견과 비슷합니다.
- 워크스페이스 내에서만 사용하는 경우 → 루트 다렉토리에 components, utils 등의 폴더로 모듈화
- `app` 라우팅 내부에서 사용하는 경우 → private 폴더로 모듈화

폴더 가독성과 각 파일의 역할이 명확해지고 사용 범위가 정해진다는 장점이 있을 거 같습니다.

**Comment by HiimKwak** [comment]
그럼 두 분의 의견의 교집합인 2번(`/manager` 한 단계 아래 - `/app`과 동일한 레벨)에 해당 워크스페이스용 컴포넌트 폴더를 놓는 걸로 컨벤션을 정하고 싶은데 다들 괜찮으신가요?

그리고 제 생각엔 우선 관객과 매니저 사이드 개발을 각각 진행한 다음에 어느정도 구색이 갖춰지면 그 때 중복되는 모듈을 packages로 빼는게 좋을 것 같습니다. 지금부터 공통으로 묶일 모듈을 미리 빼놓기엔 여러가지 비효율(뺴놨는데 한 쪽에서만 쓰인다든지 등)이 발생할 수도 있을거라 우려돼서요. 어떠신가요?

**Comment by ohprettyhak** [comment]
좋습니다! 공통 모듈 개발을 기다리면서 진행하면 속도가 느려질 거 같네요. 나중에 중복만 거르는 방식이 좋을듯합니다.
